name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libegl1 libxkbcommon-x11-0 libxcb-xinerama0
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-benchmark pytest-xdist bandit safety ruff
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml --maxfail=5 -n auto
      env:
        DISPLAY: :99
        QT_QPA_PLATFORM: offscreen
        QT_LOGGING_RULES: "*.debug=false"
    
    - name: Code quality check
      run: |
        bandit -r src/ || true
        safety check || true
        ruff check src/ || true
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml