name: Quality Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-benchmark bandit safety ruff
    
    - name: Setup virtual display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libegl1 libxkbcommon-x11-0
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
    - name: Coverage quality gate
      run: |
        export QT_QPA_PLATFORM=offscreen
        # 全体85%・コアロジック90%カバレッジ要求
        pytest tests/unit/core/test_core_coverage_focused.py --cov=src/core --cov-fail-under=85
      env:
        DISPLAY: :99
    
    - name: Performance quality gate
      run: |
        # ベンチマーク比較・10%以内性能劣化検出
        pytest tests/performance/ --benchmark-compare-fail=mean:10%
    
    - name: Security quality gate
      run: |
        # セキュリティチェック
        bandit -r src/ -f json -o bandit-report.json
        
        # 依存関係セキュリティチェック
        safety check --json --output safety-report.json
        
        # コード品質メトリクス
        ruff check src/ --format=json --output-file=ruff-report.json
    
    - name: Upload quality reports
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          bandit-report.json
          safety-report.json
          ruff-report.json